//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mgWinChart
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resChart {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resChart() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_BaseWinProject.Win.Common.WinChart.resChart", typeof(resChart).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap box_white {
            get {
                object obj = ResourceManager.GetObject("box_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoAnnotationLayout_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoAnnotationLayout_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoArea3D_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoArea3D_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoAreas_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoAreas_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoAreaStacked_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoAreaStacked_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoAreaStacked3D_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoAreaStacked3D_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoAreaStackedFull_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoAreaStackedFull_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoAreaStackedFull3D_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoAreaStackedFull3D_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoBarAndArea3D_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoBarAndArea3D_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoBarAndLine_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoBarAndLine_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoBarSideBySide_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoBarSideBySide_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoBarSideBySide3D_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoBarSideBySide3D_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoBarStacked_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoBarStacked_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoBarStacked3D_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoBarStacked3D_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoBarStackedFull_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoBarStackedFull_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoBarStackedFull3D_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoBarStackedFull3D_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoBubble_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoBubble_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoCandleStick_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoCandleStick_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoChartTitles_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoChartTitles_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoCustomDrawAxisLabels_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoCustomDrawAxisLabels_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoCustomDrawLegend_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoCustomDrawLegend_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoCustomDrawSeriesPoints_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoCustomDrawSeriesPoints_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoDataBindingChart_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoDataBindingChart_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoDataBindingSeries_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoDataBindingSeries_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoDataBindingTag_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoDataBindingTag_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoDateTimeGridAlignment_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoDateTimeGridAlignment_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoDateTimeMeasureUnits_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoDateTimeMeasureUnits_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoDateTimeScaleMode_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoDateTimeScaleMode_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoDiagramToPoint_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoDiagramToPoint_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoDisplayPatterns_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoDisplayPatterns_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoDoughnut_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoDoughnut_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoDoughnut3D_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoDoughnut3D_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoDrillDown_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoDrillDown_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoEmptyPoints_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoEmptyPoints_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoFibonacciIndicators_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoFibonacciIndicators_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoFunnel_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoFunnel_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoFunnel3D_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoFunnel3D_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoGantt_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoGantt_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoHitTesting_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoHitTesting_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoHorizontalPanes_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoHorizontalPanes_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoImageAnnotation_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoImageAnnotation_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoLargeDataSource_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoLargeDataSource_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoLegendLikeTable_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoLegendLikeTable_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoLine_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoLine_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoLine3D_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoLine3D_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoLogarithmicScale_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoLogarithmicScale_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoManhattanBar_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoManhattanBar_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoMovingAverage_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoMovingAverage_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoPie_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoPie_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoPie3D_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoPie3D_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoPoint_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoPoint_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoPolarArea_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoPolarArea_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoPolarLine_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoPolarLine_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoPolarPoint_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoPolarPoint_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoRadarArea_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoRadarArea_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoRadarDiagramToPoint_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoRadarDiagramToPoint_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoRadarLine_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoRadarLine_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoRadarPoint_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoRadarPoint_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoRangeBar_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoRangeBar_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoRealtimeChart_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoRealtimeChart_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoRegressionLine_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoRegressionLine_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoResolveOverlappingLine_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoResolveOverlappingLine_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoResolveOverlappingPie3D_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoResolveOverlappingPie3D_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoScaleBreaks_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoScaleBreaks_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoScatterLine_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoScatterLine_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoScrollingAndZooming_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoScrollingAndZooming_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoSecondaryAxes_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoSecondaryAxes_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoSeriesTitles_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoSeriesTitles_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoSideBySideBarStacked_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoSideBySideBarStacked_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoSideBySideBarStacked3D_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoSideBySideBarStacked3D_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoSideBySideBarStackedFull_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoSideBySideBarStackedFull_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoSideBySideBarStackedFull3D_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoSideBySideBarStackedFull3D_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoSideBySideGantt_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoSideBySideGantt_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoSideBySideRangeBar_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoSideBySideRangeBar_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoSpline_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoSpline_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoSpline3D_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoSpline3D_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoSplineArea_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoSplineArea_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoSplineArea3D_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoSplineArea3D_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoSplineAreaStacked_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoSplineAreaStacked_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoSplineAreaStacked3D_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoSplineAreaStacked3D_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoSplineAreaStackedFull_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoSplineAreaStackedFull_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoSplineAreaStackedFull3D_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoSplineAreaStackedFull3D_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoStepLine_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoStepLine_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoStepLine3D_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoStepLine3D_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoStock_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoStock_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoSummarization_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoSummarization_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoTextAnnotation_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoTextAnnotation_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoTopNOptions_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoTopNOptions_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoTrendlines_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoTrendlines_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartDemoVerticalPanes_Icon {
            get {
                object obj = ResourceManager.GetObject("ChartDemoVerticalPanes_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
